### PR TITLE
Add wait for deployment completion

### PR DESCRIPTION
**Pull request by obsoleted**

### CODE REVIEW

**Comment by obsoleted** [comment]
With more investigation maybe this should use logic that matches the cli: https://github.com/Azure/azure-xplat-cli/blob/383fff14973fb020c0fc6df9e51b7aefd0a7038b/lib/commands/arm/group/group.deployment._js#L72

So just spinning while the state is `Running` or `Accepted`. Unfortunately I'm not so sure this covers all "in progress" states. https://msdn.microsoft.com/library/azure/dn790565.aspx seemed to indicate that other values were possible.

**Comment by obsoleted** [comment]
The create_or_update result returns from `result()` with a provisioning_state of `Accepted`

I suppose this is because it is tracking the result of the create not the result of the deployment.

If i change `deploy_template` to do something like this:

``` python
        client.resource_groups.create_or_update(group_name, params)
        result = client.deployments.create_or_update(group_name, deployment_name, deploy_parameter)
        deployment_result = result.result() # Blocking wait, return the Deployment object
        bundledResult = dict(create_result=deployment_result)
        if module.params.get('wait_for_deployment_completion'):
            while not deployment_result.properties.provisioning_state in {'Canceled', 'Failed', 'Deleted', 'Succeeded'}:
                deployment_result = client.deployments.get(group_name, deployment_name)
                time.sleep(module.params.get('wait_for_deployment_polling_period'))
        bundledResult['get_result'] = deployment_result
        return bundledResult
```

I get the following

bundledResult['get_result'].properties.provisioning_state => 'Succeeded'
bundledResult['create_result'] => 'Accepted'

So i think we still need to give the option to wait for the get result to end up in a stable state. (And probably throw an error if not succeeded)

**Comment by lmazuel** [comment]
Interesting, do you think waiting for Succeeded should be integrated in the 'result/wait' method?

**Comment by obsoleted** [comment]
I don't have strong opinions about changing the behavior of the create_or_update result. Though the current behavior can be a bit misleading it does allow the flexibility of returning at the Accepted state which is probably useful to some folks, especially those that have no interest in waiting for the full deployment but want to make sure it is valid at least.

Since it seems like the cli and other clients probably expect and are used to the current behavior it probably shouldn't be changed.

For this module waiting until Succeeded or some failure case seems useful and polling the get response seems like an OK way to achieve this. We can then perhaps gather more deployment error information and return it when the deployment fails. Right now the behavior is a generic failure and we have to go to the portal to get more information.

**Comment by lmazuel** [comment]
@huguesv @annatisch I think this discussion will interest you

**Comment by lmazuel** [comment]
@obsoleted Do you think you can update your PR to be mergeable?

**Comment by obsoleted** [comment]
Yes, will do soon.

**Comment by obsoleted** [comment]
Updated

**Pull request merged**
